### PR TITLE
Support Windows

### PR DESCRIPTION
**Pull request by danielfrg**
Adds build script for windows.

### CODE REVIEW

**Comment by danielfrg** [comment]
It turns out M2crypto doesn't build on windows at the moment: https://gitlab.com/m2crypto/m2crypto/issues/57

**Comment by jakirkham** [comment]
Closing this to stop CIs. Please fork the feedstock and the changes to a branch on your fork. Changes made on the main feedstock result in automatic deployment, which is undesirable.

**Comment by jakirkham** [comment]
Sorry for the abrupt and inconvenient nature of this. Trying to save you some suffering later. Please read this [section]( https://github.com/conda-forge/m2crypto-feedstock#updating-m2crypto-feedstock ) of the Readme.

**Comment by jakirkham** [comment]
Maybe encountering this common misconception again will encourage me or someone else to finally require explicitly whitelisting of branches to match with one's intuition about these things. ( https://github.com/conda-forge/conda-forge.github.io/issues/87 )

**Comment by danielfrg** [comment]
Ah! sorry about that. It was definitely not what I was expecting. Moving this work to a fork now.

**Comment by jakirkham** [comment]
No worries. This is really on us for not making this clearer or at least more robust. I try to remind people about this before merging to staged-recipes, but frequently I forget.

**Pull request closed without merging**
