### PR TITLE
Support windows

### PR DESCRIPTION
**Pull request by danielfrg**
Adds build script for windows.

It turns out M2crypto doesn't build on windows at the moment: https://gitlab.com/m2crypto/m2crypto/issues/57

There is some available binaries: https://docs.saltstack.com/en/latest/topics/installation/windows.html
These binaries are probably based on a fork: https://github.com/dsoprea/M2CryptoWin64

### CODE REVIEW

**Comment by pelson** [comment]
Looks like there are some issues on AppVeyor:

```
SWIG/_m2crypto_wrap.c(3966) : warning C4244: '=' : conversion from 'Py_ssize_t' to 'int', possible loss of data 
SWIG/_m2crypto_wrap.c(4014) : warning C4244: '=' : conversion from 'Py_ssize_t' to 'int', possible loss of data 
SWIG/_m2crypto_wrap.c(4224) : warning C4244: 'return' : conversion from 'Py_ssize_t' to 'int', possible loss of data 
SWIG/_m2crypto_wrap.c(4598) : warning C4267: 'return' : conversion from 'size_t' to 'int', possible loss of data 
SWIG/_m2crypto_wrap.c(4655) : warning C4267: 'function' : conversion from 'size_t' to 'long', possible loss of data 
SWIG/_m2crypto_wrap.c(6407) : fatal error C1083: Cannot open include file: 'poll.h': No such file or directory 
error: command 'C:\\Users\\appveyor\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2
Command failed: C:\Windows\system32\cmd.exe /c call bld.bat

```

Looks like `poll` is [problematic](http://stackoverflow.com/questions/15985179/header-file-for-the-function-poll) on Windows...

**Comment by danielfrg** [comment]
Yes, something needs to get fixed on m2crypto for it to work on windows see: https://gitlab.com/m2crypto/m2crypto/issues/57.  I don't think this is going to happen soon.

Libraries that depend on m2crypto on windows (salt for example) have been using a fork (https://github.com/dsoprea/M2CryptoWin64) that works on windows but its (very) outdated. I was thing on creating the recipe for the fork but I supposed I should other feedstock since its another library?

**Comment by pelson** [comment]
> I was thing on creating the recipe for the fork but I supposed I should other feedstock since its another library?

Because m2crypto doesn't support windows, and m2cryptowin64 doesn't support anything but windows, I'm inclined to suggest that m2cryptowin64 is simply the version used on windows (and is therefore the same package). This kind of thing can be done in conda recipes with selectors. See [pyke-feedstock](https://github.com/conda-forge/pyke-feedstock/blob/master/recipe/meta.yaml#L5) for an example of splitting the source depending on a selector (in pyke's case based on py2k vs py3k).

**Comment by danielfrg** [comment]
Ok, that should make things even easier for me so i'll do that. Hopefully find some time next week. Thanks for the input.

**Comment by danielfrg** [comment]
Actually one question. Do you know if the `meta.yaml` renders jinja completely? I know it can set variables `{% set version = "0.24.0" %}` so i am assuming it can also do if statements. I ask this because the version is now going to depend on the platform. The last one on windows will be `0.21` from `m2cryptowin64 ` and on OS X and linux it will be the `0.24.0` currently from `M2crypto`. If it can render if statements how can I check the current platform that is going to be used?

**Comment by pelson** [comment]
> Actually one question. Do you know if the meta.yaml renders jinja completely? I know it can set variables {% set version = "0.24.0" %} so i am assuming it can also do if statements.

It is possible to use jinja if statements, though is quite unusual, as selectors pretty much do the same job and are more convenient.

> I ask this because the version is now going to depend on the platform. 

That seems reasonable - I'd still use conda-build selectors though (ala the pyke example from above).

**Comment by pelson** [comment]
Really nice. 👍

**Pull request merged**
